name: Benchmark Test

on:
  repository_dispatch:
    types: [new_ai_benchmark_build_test]

jobs:
  test-benchmark:
    uses: ./.github/workflows/benchmark.yml
    with:
      data_branch: data-test
  secrets: inherit