name: "DEV: Test Present Benchmark Result"
on: 
  workflow_dispatch:
    inputs:
      test_version:
        description: 'Version you just mocked'
        required: true
        default: 'v0.0.0-test'

jobs:
  run-present-benchmark-result:
    uses: ./.github/workflows/present-benchmark-result.yml
    with:
      app_version: ${{ github.event.inputs.test_version }}
    secrets: inherit