name: "DEV: Test Benchmark Result"

on: 
  workflow_dispatch:
    inputs:
      mock_version:
        description: 'Version tag to mock and test'
        required: true
        default: 'v0.0.0-test.0'

jobs:
  run-present-benchmark-result:
    uses: ./.github/workflows/present-benchmark-result.yml
    with:
      app_version: ${{ inputs.mock_version }}
    secrets: inherit